/*

This file is part of Ext JS 4

Copyright (c) 2011 Sencha Inc

Contact:  http://www.sencha.com/contact

GNU General Public License Usage
This file may be used under the terms of the GNU General Public License version 3.0 as published by the Free Software Foundation and appearing in the file LICENSE included in the packaging of this file.  Please review the following information to ensure the GNU General Public License version 3.0 requirements will be met: http://www.gnu.org/copyleft/gpl.html.

If you are unsure which license is appropriate for your use, please contact the sales department at http://www.sencha.com/contact.

*/
/* This file is automatically generated by create_language_js.py */

// some data used in the examples
Ext.namespace('Ext.exampledata');

Ext.exampledata.languages = [
	['af', 'Afrikaans', 'ISO-8859-2'],
	['bg', 'Bulgarian', 'utf-8'],
	['ca', 'Catalonian', 'ascii'],
	['cs', 'Czech', 'utf-8'],
	['da', 'Danish', 'utf-8'],
	['de', 'German', 'utf-8'],
	['el_GR', 'Greek', 'utf-8'],
	['en_GB', 'English (UK)', 'ascii'],
	['en', 'English', 'ascii'],
	['es', 'Spanish/Latin American', 'utf-8'],
	['fa', 'Farsi (Persian)', 'utf-8'],
	['fi', 'Finnish', 'utf-8'],
	['fr_CA', 'France (Canadian)', 'utf-8'],
	['fr', 'France (France)', 'utf-8'],
	['gr', 'Greek (Old Version)', 'utf-8'],
	['he', 'Hebrew', 'windows-1255'],
	['hr', 'Croatian', 'utf-8'],
	['hu', 'Hungarian', 'utf-8'],
	['id', 'Indonesian', 'ascii'],
	['it', 'Italian', 'ascii'],
	['ja', 'Japanese', 'utf-8'],
	['ko', 'Korean', 'utf-8'],
	['lt', 'Lithuanian', 'utf-8'],
	['lv', 'Latvian', 'utf-8'],
	['mk', 'Macedonia', 'utf-8'],
	['nl', 'Dutch', 'ascii'],
	['no_NB', 'Norwegian Bokmål', 'utf-8'],
	['no_NN', 'Norwegian Nynorsk', 'utf-8'],
	['pl', 'Polish', 'utf-8'],
	['pt_BR', 'Portuguese/Brazil', 'ascii'],
	['pt_PT', 'Portuguese/Portugal', 'ascii'],
	['ro', 'Romanian', 'utf-8'],
	['ru', 'Russian', 'UTF-8'],
	['sk', 'Slovak', 'utf-8'],
	['sl', 'Slovenian', 'utf-8'],
	['sr_RS', 'Serbian Cyrillic', 'UTF-8'],
	['sr', 'Serbian Latin', 'utf-8'],
	['sv_SE', 'Swedish', 'utf-8'],
	['th', 'Thailand', 'utf-8'],
	['tr', 'Turkish', 'utf-8'],
	['ukr', 'Ukrainian', 'UTF-8'],
	['vn', 'Vietnamese', 'UTF-8'],
	['zh_CN', 'Simplified Chinese', 'utf-8'],
	['zh_TW', 'Traditional Chinese', 'UTF-8']
];

